### ISSUE TITLE
405 error when loading / <-- is this us? a malicious actor?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#128]
**[Replicate here](https://[::ffff:a9fe:a9fe]/)**

When accessing `/`, there's a 405 error. The traceback says:

```python
Traceback (most recent call last):
  File "/home/webadmin/getting-unstuck-web/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/webadmin/getting-unstuck-web/env/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/webadmin/getting-unstuck-web/env/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/webadmin/getting-unstuck-web/env/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/webadmin/getting-unstuck-web/env/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

```

**Comment by jsarchibald** [comment]
Security software from HUIT’s side, I think, but raising an error for weird stuff like that is entirely expected and actually good security.
